[package]
name = "fuzzy"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.21", features = ["derive"] }
rust-i18n = "3.1.2"
stringcase = "0.3.0"
tetra = "0.8.0"

[lib]
name = "flib"
path = "flib/lib.rs"
